name: Build APK For Mehrab Sir
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # এই স্টেপটি আপনার জন্য সব প্রয়োজনীয় প্যাকেজ অটোমেটিক সেট করে দেবে
      - name: Build with Buildozer
        uses: ArtemSerebrennikov/buildozer-action@v1
        with:
          buildozer_version: stable
          command: buildozer android debug

      # অ্যাপ তৈরি হয়ে গেলে সেটি সেভ করা
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
