name: Build Empty App
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Basic Tools
        run: |
          # সব আপডেট এড়িয়ে শুধু প্রয়োজনীয় টুলস
          sudo apt update --fix-missing
          sudo apt install -y openjdk-17-jdk zip unzip bzip2 libncurses5 libstdc++6
          pip install --user --upgrade Cython==0.29.33 buildozer kivy

      - name: Create App Skeleton
        run: |
          export PATH=$PATH:~/.local/bin
          # এটি জোরাজুরি করে খোলটা বের করে আনবে এবং অদরকারি ডাউনলোড কমাবে
          yes | buildozer android debug

      - name: Export APK
        uses: actions/upload-artifact@v4
        with:
          name: MyEmptyApp
          path: bin/*.apk
