name: Build APK For Mehrab Sir
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        # আমরা সরাসরি এই অ্যাকশনটি ব্যবহার করছি যা সবচেয়ে হালকা
        uses: ArtemSerebrennikov/buildozer-action@v1
        with:
          buildozer_version: stable
          command: buildozer android debug
          # বিল্ডোজারকে বলছি যেন সে কোনো কিছু আপডেট না করে সরাসরি বিল্ড দেয়
          buildozer_flags: --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
