name: Skeleton Build Final
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Basic Setup
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk python3-pip zip unzip
          pip install --user --upgrade Cython==0.29.33 buildozer kivy

      - name: Create Skeleton
        run: |
          export PATH=$PATH:~/.local/bin
          # এটি জোরাজুরি করে খোলটি বের করে আনবে
          yes | buildozer android debug

      - name: Download My APK
        uses: actions/upload-artifact@v4
        with:
          name: MyEmptyApp
          path: bin/*.apk
