name: Build Empty Skeleton
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Essential Tools
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk python3-pip zip unzip
          pip install --user --upgrade Cython==0.29.33 buildozer kivy

      - name: Create Skeleton APK
        run: |
          export PATH=$PATH:~/.local/bin
          # শুধু খোলটা বানানোর কমান্ড
          yes | buildozer android debug

      - name: Save My APK
        uses: actions/upload-artifact@v4
        with:
          name: EmptyApp
          path: bin/*.apk
