name: Build Skeleton
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Tools
        run: |
          # 404 এরর এড়াতে মিরর ঠিক করা
          sudo apt update --fix-missing
          sudo apt install -y openjdk-17-jdk zip unzip
          pip install --user --upgrade Cython==0.29.33 buildozer kivy

      - name: Create Skeleton
        run: |
          export PATH=$PATH:~/.local/bin
          # শুধু খোল তৈরির জন্য দ্রুত কমান্ড
          yes | buildozer android debug

      - name: Upload Skeleton
        uses: actions/upload-artifact@v4
        with:
          name: MySkeletonApp
          path: bin/*.apk
